name: End-to-End Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Ensure this matches the version required by your Netlify CLI
      - name: Create .env.local file
        run: |
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.local
          echo MONGODB_DATABASE = "tasks_netlify" >> .env.local
          echo MONGODB_COLLECTION = "tasks" >> .env.local

      - name: Install project dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Start Netlify server in the background
        run: netlify dev &> netlify.log &
        shell: bash

      - name: Wait for Netlify server to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8888; do
            echo "Waiting for Netlify server..."
            sleep 5
          done

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          CI: true

      - name: Upload Cypress screenshots
        if: failure() # Only upload screenshots if the job failed
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Netlify logs
        uses: actions/upload-artifact@v2
        if: always() # or use `failure()` to upload only if the job fails
        with:
          name: netlify-logs
          path: netlify.log
